/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Option } from "./Option";
import { OptionCountArgs } from "./OptionCountArgs";
import { OptionFindManyArgs } from "./OptionFindManyArgs";
import { OptionFindUniqueArgs } from "./OptionFindUniqueArgs";
import { CreateOptionArgs } from "./CreateOptionArgs";
import { UpdateOptionArgs } from "./UpdateOptionArgs";
import { DeleteOptionArgs } from "./DeleteOptionArgs";
import { Question } from "../../question/base/Question";
import { OptionService } from "../option.service";
@graphql.Resolver(() => Option)
export class OptionResolverBase {
  constructor(protected readonly service: OptionService) {}

  async _optionsMeta(
    @graphql.Args() args: OptionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Option])
  async options(@graphql.Args() args: OptionFindManyArgs): Promise<Option[]> {
    return this.service.options(args);
  }

  @graphql.Query(() => Option, { nullable: true })
  async option(
    @graphql.Args() args: OptionFindUniqueArgs
  ): Promise<Option | null> {
    const result = await this.service.option(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Option)
  async createOption(@graphql.Args() args: CreateOptionArgs): Promise<Option> {
    return await this.service.createOption({
      ...args,
      data: {
        ...args.data,

        question: args.data.question
          ? {
              connect: args.data.question,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Option)
  async updateOption(
    @graphql.Args() args: UpdateOptionArgs
  ): Promise<Option | null> {
    try {
      return await this.service.updateOption({
        ...args,
        data: {
          ...args.data,

          question: args.data.question
            ? {
                connect: args.data.question,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Option)
  async deleteOption(
    @graphql.Args() args: DeleteOptionArgs
  ): Promise<Option | null> {
    try {
      return await this.service.deleteOption(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Question, {
    nullable: true,
    name: "question",
  })
  async getQuestion(
    @graphql.Parent() parent: Option
  ): Promise<Question | null> {
    const result = await this.service.getQuestion(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
