/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { QuestionService } from "../question.service";
import { QuestionCreateInput } from "./QuestionCreateInput";
import { Question } from "./Question";
import { QuestionFindManyArgs } from "./QuestionFindManyArgs";
import { QuestionWhereUniqueInput } from "./QuestionWhereUniqueInput";
import { QuestionUpdateInput } from "./QuestionUpdateInput";
import { ExplanationFindManyArgs } from "../../explanation/base/ExplanationFindManyArgs";
import { Explanation } from "../../explanation/base/Explanation";
import { ExplanationWhereUniqueInput } from "../../explanation/base/ExplanationWhereUniqueInput";
import { OptionFindManyArgs } from "../../option/base/OptionFindManyArgs";
import { Option } from "../../option/base/Option";
import { OptionWhereUniqueInput } from "../../option/base/OptionWhereUniqueInput";

export class QuestionControllerBase {
  constructor(protected readonly service: QuestionService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Question })
  async createQuestion(
    @common.Body() data: QuestionCreateInput
  ): Promise<Question> {
    return await this.service.createQuestion({
      data: {
        ...data,

        quiz: data.quiz
          ? {
              connect: data.quiz,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        quiz: {
          select: {
            id: true,
          },
        },

        text: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Question] })
  @ApiNestedQuery(QuestionFindManyArgs)
  async questions(@common.Req() request: Request): Promise<Question[]> {
    const args = plainToClass(QuestionFindManyArgs, request.query);
    return this.service.questions({
      ...args,
      select: {
        createdAt: true,
        id: true,

        quiz: {
          select: {
            id: true,
          },
        },

        text: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Question })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async question(
    @common.Param() params: QuestionWhereUniqueInput
  ): Promise<Question | null> {
    const result = await this.service.question({
      where: params,
      select: {
        createdAt: true,
        id: true,

        quiz: {
          select: {
            id: true,
          },
        },

        text: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Question })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateQuestion(
    @common.Param() params: QuestionWhereUniqueInput,
    @common.Body() data: QuestionUpdateInput
  ): Promise<Question | null> {
    try {
      return await this.service.updateQuestion({
        where: params,
        data: {
          ...data,

          quiz: data.quiz
            ? {
                connect: data.quiz,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          quiz: {
            select: {
              id: true,
            },
          },

          text: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Question })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteQuestion(
    @common.Param() params: QuestionWhereUniqueInput
  ): Promise<Question | null> {
    try {
      return await this.service.deleteQuestion({
        where: params,
        select: {
          createdAt: true,
          id: true,

          quiz: {
            select: {
              id: true,
            },
          },

          text: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/explanations")
  @ApiNestedQuery(ExplanationFindManyArgs)
  async findExplanations(
    @common.Req() request: Request,
    @common.Param() params: QuestionWhereUniqueInput
  ): Promise<Explanation[]> {
    const query = plainToClass(ExplanationFindManyArgs, request.query);
    const results = await this.service.findExplanations(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        question: {
          select: {
            id: true,
          },
        },

        text: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/explanations")
  async connectExplanations(
    @common.Param() params: QuestionWhereUniqueInput,
    @common.Body() body: ExplanationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      explanations: {
        connect: body,
      },
    };
    await this.service.updateQuestion({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/explanations")
  async updateExplanations(
    @common.Param() params: QuestionWhereUniqueInput,
    @common.Body() body: ExplanationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      explanations: {
        set: body,
      },
    };
    await this.service.updateQuestion({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/explanations")
  async disconnectExplanations(
    @common.Param() params: QuestionWhereUniqueInput,
    @common.Body() body: ExplanationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      explanations: {
        disconnect: body,
      },
    };
    await this.service.updateQuestion({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/options")
  @ApiNestedQuery(OptionFindManyArgs)
  async findOptions(
    @common.Req() request: Request,
    @common.Param() params: QuestionWhereUniqueInput
  ): Promise<Option[]> {
    const query = plainToClass(OptionFindManyArgs, request.query);
    const results = await this.service.findOptions(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        isCorrect: true,

        question: {
          select: {
            id: true,
          },
        },

        text: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/options")
  async connectOptions(
    @common.Param() params: QuestionWhereUniqueInput,
    @common.Body() body: OptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      options: {
        connect: body,
      },
    };
    await this.service.updateQuestion({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/options")
  async updateOptions(
    @common.Param() params: QuestionWhereUniqueInput,
    @common.Body() body: OptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      options: {
        set: body,
      },
    };
    await this.service.updateQuestion({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/options")
  async disconnectOptions(
    @common.Param() params: QuestionWhereUniqueInput,
    @common.Body() body: OptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      options: {
        disconnect: body,
      },
    };
    await this.service.updateQuestion({
      where: params,
      data,
      select: { id: true },
    });
  }
}
